//===- CharybdisOps.h - Charybdis op declarations ------------------------===//
//
// Declares the C++ op classes for all ops in the charybdis (kbd) dialect.
// The class bodies are generated by mlir-tblgen from CharybdisOps.td and
// emitted into the build tree as CharybdisOps.h.inc.
//
//===----------------------------------------------------------------------===//

#ifndef CHARYBDIS_CHARYBDISOPS_H
#define CHARYBDIS_CHARYBDISOPS_H

#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/Dialect.h"
#include "mlir/IR/OpDefinition.h"
#include "mlir/Interfaces/SideEffectInterfaces.h"

// The dialect header must be included before the op declarations because
// the op classes reference CharybdisDialect in their base class template.
#include "charybdis/CharybdisDialect.h"

// Pull in the tblgen-generated op class declarations (IdentityOp, etc.).
#define GET_OP_CLASSES
#include "charybdis/CharybdisOps.h.inc"

#endif // CHARYBDIS_CHARYBDISOPS_H
