//===- CharybdisDialect.h - Charybdis dialect declaration ----------------===//
//
// Declares the CharybdisDialect C++ class. The class body is generated by
// mlir-tblgen from CharybdisDialect.td and emitted into the build tree as
// CharybdisDialect.h.inc, which is included below.
//
//===----------------------------------------------------------------------===//

#ifndef CHARYBDIS_CHARYBDISDIALECT_H
#define CHARYBDIS_CHARYBDISDIALECT_H

#include "mlir/IR/Dialect.h"

// Include the tblgen-generated dialect class declaration.
// This file lives in the build tree (include/charybdis/CharybdisDialect.h.inc)
// and is created by the MLIRCharybdisOpsIncGen target.
#include "charybdis/CharybdisDialect.h.inc"

#endif // CHARYBDIS_CHARYBDISDIALECT_H
